export enum PageEnum {
  LOGIN = '/signin',
  HOME = '/home',
  ERROR_PAGE = '/not-found',
  LANDING = '/',
  OAUTH_LANDING = '/login/oauth',
  PLANT_DETAILS = '/plant/:id',
  SEARCH_RESULT = '/search',
  My_PAGE = '/me',
  QNABOARD = '/qna',
  QNABOARD_DETAIL = '/qna/detail/:id',
  QNABOARD_EDIT = '/qna/edit',
  LOGOUT = '/logout',
  WATER_GUIDE = '/guide/water',
  VENTILATION_GUIDE = '/guide/ventilation',
  SUNLIGHT_GUIDE = '/guide/sunlight',
  BLIGHT_GUIDE = '/guide/blight',
  ALL_PLANTS = '/plants',
  SEED_STORE = '/seed',
  STORY_DETAIL = '/story/detail/:id',
  STORY_REGISTER = '/story/register',
  STORY_FEED = '/story/feed',
}
export enum PageNameEnum {
  LOGIN = 'Sign In',
  HOME = 'Home',
  ERROR_PAGE = 'NOT FOUND - 404',
  LANDING = 'Load Page...',
  OAUTH_LANDING = 'Logging On...',
  PLANT_DETAILS = 'Plant details',
  SEARCH_RESULT = 'Search result',
  My_PAGE = 'My page',
  SETTING = 'My Page - Setting',
  My_Plant = 'My Page - My Plant',
  MY_QNA = 'My Page - My QnA',
  QNABOARD = 'QNA Board',
  QNABOARD_DETAIL = 'QNA Board - Detail',
  QNABOARD_EDIT = 'QNA Board - Edit',
  LOGOUT = 'Sign Out',
  WATER_GUIDE = 'Guide - Water',
  VENTILATION_GUIDE = 'Guide - Ventilation',
  SUNLIGHT_GUIDE = 'Guide - Sunlight',
  BLIGHT_GUIDE = 'Guide - Blight',
  PLANTS = 'All Plants',
  SEED_STORE = 'Seed Store',
  STORY_DETAIL = 'Story Detail',
  STORY_REGISTER = 'Story Register',
  STORY_FEED = 'Story Feed',
}
export enum LayoutEnum {
  DEFAULT = 'Default',
  FILLED = 'Filled',
}
